# Generated by Django 2.0.4 on 2018-08-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20180403_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='show_newsletter_signup',
            field=models.BooleanField(default=True),
        ),
    ]
