# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-16 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20171207_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='photo',
            new_name='main_photo',
        ),
    ]
