# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('petpoint_id', models.PositiveIntegerField(verbose_name='petpoint animal id')),
                ('name', models.CharField(max_length=200)),
                ('species', models.CharField(blank=True, max_length=200)),
                ('sex', models.CharField(max_length=10)),
                ('primary_breed', models.CharField(blank=True, max_length=100)),
                ('secondary_breed', models.CharField(blank=True, max_length=100)),
                ('primary_color', models.CharField(blank=True, max_length=100)),
                ('secondary_color', models.CharField(blank=True, max_length=100)),
                ('age', models.PositiveSmallIntegerField(verbose_name='age in months')),
                ('size', models.CharField(max_length=3)),
                ('description', models.TextField(blank=True)),
                ('photo_1_url', models.URLField(blank=True)),
                ('photo_2_url', models.URLField(blank=True)),
                ('photo_3_url', models.URLField(blank=True)),
                ('on_hold', models.BooleanField(default=False)),
                ('special_needs', models.CharField(max_length=100)),
                ('no_dogs', models.BooleanField(default=False)),
                ('no_cats', models.BooleanField(default=False)),
                ('no_kids', models.BooleanField(default=False)),
                ('lived_with_kids', models.CharField(max_length=10)),
                ('lived_with_animals', models.CharField(max_length=10)),
                ('lived_with_animal_types', models.CharField(max_length=200)),
                ('weight', models.CharField(blank=True, max_length=30)),
            ],
            bases=('wagtailcore.page',),
        ),
    ]
