# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_auto_20170829_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='name',
        ),
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=models.TextField(blank=True, max_length=8000),
        ),
        migrations.AlterField(
            model_name='animal',
            name='petpoint_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='petpoint animal id'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='special_needs',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
