# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 17:19
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_animalspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='photos',
            field=wagtail.wagtailcore.fields.StreamField((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()),), blank=True),
        ),
    ]
