# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_animal_photos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='photos',
            new_name='additional_photos',
        ),
    ]
