# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('animals', '0006_auto_20171117_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='main_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
