# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_animal_main_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalspage',
            name='species',
            field=models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog')], default='Cat', max_length=20),
            preserve_default=False,
        ),
    ]
