# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0009_animal_surrender_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='surrender_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
