# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0015_auto_20171207_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='adoption_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='adoption_message',
            field=models.TextField(blank=True),
        ),
    ]
