# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0017_animalcountsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalcountsettings',
            name='cats_adopted',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='animalcountsettings',
            name='cats_rescued',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='animalcountsettings',
            name='dogs_adopted',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='animalcountsettings',
            name='dogs_rescued',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
