# Generated by Django 2.0.3 on 2018-03-26 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0022_auto_20180321_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalspage',
            name='menu_item_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='menu image'),
        ),
    ]
