# Generated by Django 2.0.3 on 2018-04-03 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0023_auto_20180326_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalspage',
            name='banner_image',
            field=models.ForeignKey(blank=True, help_text='This image should be exactly 1400px wide and 370px high.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='page banner image'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['adoption_date'], name='animals_ani_adoptio_0af316_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['last_intake_date'], name='animals_ani_last_in_4a50ce_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['species', 'adoption_date', 'last_intake_date'], name='animals_ani_species_60b197_idx'),
        ),
    ]
