# Generated by Django 2.0.4 on 2018-04-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0024_auto_20180403_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='stage',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
