# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-05 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('core', '0003_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('menu_title', models.CharField(blank=True, max_length=100, verbose_name='menu title')),
                ('members', wagtail.core.fields.StreamField((('section', wagtail.core.blocks.CharBlock(classname='full title')), ('member', wagtail.core.blocks.StructBlock((('name', wagtail.core.blocks.CharBlock(max_length=50)), ('role', wagtail.core.blocks.CharBlock(max_length=50, required=False)), ('role_since', wagtail.core.blocks.CharBlock(max_length=50, required=False)), ('location', wagtail.core.blocks.CharBlock(max_length=50, required=False)), ('pets', wagtail.core.blocks.CharBlock(max_length=100, required=False)), ('bio', wagtail.core.blocks.TextBlock()), ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('photo_caption', wagtail.core.blocks.CharBlock(max_length=50)))))), blank=True)),
            ],
            options={
                'verbose_name': 'Team Page',
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
