# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-05 20:08
from __future__ import unicode_literals

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_teampage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teampage',
            name='members',
            field=wagtail.fields.StreamField((('section', wagtail.blocks.CharBlock(classname='full title')), ('member', wagtail.blocks.StructBlock((('name', wagtail.blocks.CharBlock(max_length=50)), ('role', wagtail.blocks.CharBlock(max_length=50, required=False)), ('role_since', wagtail.blocks.CharBlock(max_length=50, required=False)), ('location', wagtail.blocks.CharBlock(max_length=50, required=False)), ('pets', wagtail.blocks.CharBlock(max_length=100, required=False)), ('bio', wagtail.blocks.TextBlock()), ('photo', wagtail.images.blocks.ImageChooserBlock(required=False)), ('photo_caption', wagtail.blocks.CharBlock(max_length=50, required=False)))))), blank=True),
        ),
    ]
