# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 23:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('core', '0005_auto_20170905_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Parent Page with No Content',
            },
            bases=('wagtailcore.page',),
        ),
    ]
