# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 22:43
from __future__ import unicode_literals

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20171128_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adoptioncentre',
            options={'verbose_name': 'Adoption Centre'},
        ),
        migrations.RemoveField(
            model_name='adoptioncentre',
            name='picture_blocks',
        ),
        migrations.AddField(
            model_name='adoptioncentre',
            name='body',
            field=wagtail.fields.StreamField((('picture_links', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock((('title', wagtail.blocks.CharBlock(max_length=50)), ('image', wagtail.images.blocks.ImageChooserBlock()), ('page', wagtail.blocks.PageChooserBlock()))))),), blank=True),
        ),
    ]
