# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-12 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20171212_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='teampage',
            name='group1_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
