# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-12 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_teampage_group1_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='teampage',
            name='group2_members',
            field=wagtail.wagtailcore.fields.StreamField((('member', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock(max_length=50)), ('role', wagtail.wagtailcore.blocks.CharBlock(max_length=50, required=False)), ('role_since', wagtail.wagtailcore.blocks.CharBlock(max_length=50, required=False)), ('location', wagtail.wagtailcore.blocks.CharBlock(max_length=50, required=False)), ('pets', wagtail.wagtailcore.blocks.CharBlock(max_length=100, required=False)), ('bio', wagtail.wagtailcore.blocks.TextBlock()), ('photo', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), ('photo_caption', wagtail.wagtailcore.blocks.CharBlock(max_length=50, required=False))))),), blank=True, verbose_name='members'),
        ),
        migrations.AddField(
            model_name='teampage',
            name='group2_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='teampage',
            name='group3_members',
            field=wagtail.wagtailcore.fields.StreamField((('member', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock(max_length=50)), ('role', wagtail.wagtailcore.blocks.CharBlock(max_length=50, required=False)), ('role_since', wagtail.wagtailcore.blocks.CharBlock(max_length=50, required=False)), ('location', wagtail.wagtailcore.blocks.CharBlock(max_length=50, required=False)), ('pets', wagtail.wagtailcore.blocks.CharBlock(max_length=100, required=False)), ('bio', wagtail.wagtailcore.blocks.TextBlock()), ('photo', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), ('photo_caption', wagtail.wagtailcore.blocks.CharBlock(max_length=50, required=False))))),), blank=True, verbose_name='members'),
        ),
        migrations.AddField(
            model_name='teampage',
            name='group3_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='teampage',
            name='group1_members',
            field=wagtail.wagtailcore.fields.StreamField((('member', wagtail.wagtailcore.blocks.StructBlock((('name', wagtail.wagtailcore.blocks.CharBlock(max_length=50)), ('role', wagtail.wagtailcore.blocks.CharBlock(max_length=50, required=False)), ('role_since', wagtail.wagtailcore.blocks.CharBlock(max_length=50, required=False)), ('location', wagtail.wagtailcore.blocks.CharBlock(max_length=50, required=False)), ('pets', wagtail.wagtailcore.blocks.CharBlock(max_length=100, required=False)), ('bio', wagtail.wagtailcore.blocks.TextBlock()), ('photo', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False)), ('photo_caption', wagtail.wagtailcore.blocks.CharBlock(max_length=50, required=False))))),), blank=True, verbose_name='members'),
        ),
        migrations.AlterField(
            model_name='teampage',
            name='group1_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='title'),
        ),
    ]
