# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 17:52
from __future__ import unicode_literals

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20171212_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptioncentre',
            name='body',
            field=wagtail.fields.StreamField((('picture_links', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock((('title', wagtail.blocks.CharBlock(max_length=50)), ('image', wagtail.images.blocks.ImageChooserBlock()), ('page', wagtail.blocks.PageChooserBlock()))), template='core/blocks/picture_links.html')),), blank=True),
        ),
        migrations.AlterField(
            model_name='teampage',
            name='group1_members',
            field=wagtail.fields.StreamField((('member', wagtail.blocks.StructBlock((('name', wagtail.blocks.CharBlock(max_length=50)), ('role', wagtail.blocks.CharBlock(max_length=50, required=False)), ('role_since', wagtail.blocks.CharBlock(max_length=50, required=False)), ('location', wagtail.blocks.CharBlock(max_length=50, required=False)), ('pets', wagtail.blocks.CharBlock(max_length=200, required=False)), ('bio', wagtail.blocks.RichTextBlock(required=False)), ('photo', wagtail.images.blocks.ImageChooserBlock(required=False))))),), blank=True, verbose_name='members'),
        ),
        migrations.AlterField(
            model_name='teampage',
            name='group2_members',
            field=wagtail.fields.StreamField((('member', wagtail.blocks.StructBlock((('name', wagtail.blocks.CharBlock(max_length=50)), ('role', wagtail.blocks.CharBlock(max_length=50, required=False)), ('role_since', wagtail.blocks.CharBlock(max_length=50, required=False)), ('location', wagtail.blocks.CharBlock(max_length=50, required=False)), ('pets', wagtail.blocks.CharBlock(max_length=200, required=False)), ('bio', wagtail.blocks.RichTextBlock(required=False)), ('photo', wagtail.images.blocks.ImageChooserBlock(required=False))))),), blank=True, verbose_name='members'),
        ),
        migrations.AlterField(
            model_name='teampage',
            name='group3_members',
            field=wagtail.fields.StreamField((('member', wagtail.blocks.StructBlock((('name', wagtail.blocks.CharBlock(max_length=50)), ('role', wagtail.blocks.CharBlock(max_length=50, required=False)), ('role_since', wagtail.blocks.CharBlock(max_length=50, required=False)), ('location', wagtail.blocks.CharBlock(max_length=50, required=False)), ('pets', wagtail.blocks.CharBlock(max_length=200, required=False)), ('bio', wagtail.blocks.RichTextBlock(required=False)), ('photo', wagtail.images.blocks.ImageChooserBlock(required=False))))),), blank=True, verbose_name='members'),
        ),
    ]
