# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-25 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_faqindexpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FaqIndexPage',
            new_name='ContentIndexPage',
        ),
    ]
