# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_contentindexpage_empty_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentindexpage',
            name='empty_message',
            field=models.CharField(default='Empty', max_length=200),
        ),
    ]
