# Generated by Django 2.0.3 on 2018-03-12 20:36

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('core', '0027_homepage_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='events_photo',
            field=models.ForeignKey(blank=True, help_text='This image MUST BE EXACTLY 1400px by 475px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='slider',
            field=wagtail.fields.StreamField((('slider_item', wagtail.blocks.StructBlock((('title', wagtail.blocks.CharBlock(max_length=25)), ('summary', wagtail.blocks.TextBlock(max_length=60)), ('photo', wagtail.images.blocks.ImageChooserBlock(help_text='This image MUST BE EXACTLY 1400px by 475px')), ('page', wagtail.blocks.PageChooserBlock(required=False))))),), blank=True),
        ),
    ]
