# Generated by Django 2.0.3 on 2018-03-21 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20180312_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='events_photo',
            field=models.ForeignKey(blank=True, help_text='This image MUST BE EXACTLY 1400px by 530px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
