# Generated by Django 2.0.3 on 2018-04-03 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailimages', '0019_delete_filter'),
        ('core', '0031_auto_20180403_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptioncentre',
            name='cats_image',
            field=models.ForeignKey(blank=True, help_text='This image should be exactly 1400px wide and 370px high.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='dogs banner image'),
        ),
        migrations.AddField(
            model_name='adoptioncentre',
            name='cats_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='adoptioncentre',
            name='dogs_image',
            field=models.ForeignKey(blank=True, help_text='This image should be exactly 1400px wide and 370px high.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='dogs banner image'),
        ),
        migrations.AddField(
            model_name='adoptioncentre',
            name='dogs_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
