# Generated by Django 2.0.4 on 2018-08-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20180416_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentindexpage',
            name='show_newsletter_signup',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='show_newsletter_signup',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supporterspage',
            name='show_newsletter_signup',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teampage',
            name='show_newsletter_signup',
            field=models.BooleanField(default=True),
        ),
    ]
