# Generated by Django 2.0.4 on 2018-10-24 21:34

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20180810_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='slider',
            field=wagtail.fields.StreamField((('slider_item', wagtail.blocks.StructBlock((('title', wagtail.blocks.CharBlock(max_length=25, required=False)), ('summary', wagtail.blocks.TextBlock(max_length=60, required=False)), ('photo', wagtail.images.blocks.ImageChooserBlock(help_text='This image MUST BE EXACTLY 1400px by 475px')), ('page', wagtail.blocks.PageChooserBlock(required=False)), ('active', wagtail.blocks.BooleanBlock(bool=True))))),), blank=True),
        ),
    ]
