# Generated by Django 2.0.4 on 2018-10-29 18:33

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20181029_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='slider',
            field=wagtail.fields.StreamField((('slider_item', wagtail.blocks.StructBlock((('photo', wagtail.images.blocks.ImageChooserBlock(help_text='This image MUST BE EXACTLY 1400px by 550px')), ('page', wagtail.blocks.PageChooserBlock(required=False)), ('external_url', wagtail.blocks.URLBlock(required=False)), ('active', wagtail.blocks.BooleanBlock(required=False))))),), blank=True),
        ),
    ]
