# Generated by Django 2.2.24 on 2021-08-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_redirectpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformfield',
            name='clean_name',
            field=models.CharField(blank=True, default='', help_text='Safe name of the form field, the label converted to ascii_snake_case', max_length=255, verbose_name='name'),
        ),
    ]
