# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('priority', models.PositiveIntegerField()),
                ('ready', models.BooleanField(default=False)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wagtailcore.Page')),
            ],
        ),
    ]
