# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-12 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediaqueue',
            name='date',
            field=models.DateTimeField(verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='socialmediaqueue',
            name='page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='socialmediaqueue',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
